name: automated-build-android-app-with-github-action
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "Development" ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: amirisback/automated-build-android-app-with-github-action@2.2.1
